# Generated by Django 5.2.5 on 2025-08-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0002_request_status_alter_request_estimated_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='requests_pictures/'),
        ),
    ]
