# Generated by Django 5.2.5 on 2025-08-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0002_request_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='skills',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
