# Generated by Django 5.2.5 on 2025-08-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0003_request_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
