# Generated by Django 5.2.5 on 2025-08-09 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0002_request_author'),
        ('user', '0002_usertable_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aid.location'),
            preserve_default=False,
        ),
    ]
