# Generated by Django 5.2.5 on 2025-08-11 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_usertable_options_alter_usertable_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertable',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usertable',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='usertable',
            name='username',
        ),
    ]
