# Generated by Django 5.2.5 on 2025-08-11 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0004_alter_request_photo'),
        ('user', '0006_alter_usertable_options_alter_usertable_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aid.location'),
        ),
    ]
