# Generated by Django 5.2.5 on 2025-08-11 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aid', '0005_alter_request_author'),
        ('user', '0007_alter_usertable_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserTable',
        ),
    ]
